services:
  - type: web
    name: socratic-bot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: OPENAI_API_KEY
      - key: PYTHON_VERSION
        value: 3.11
